config/routes.rb
TestRails::Application.routes.draw do
  resources :cards

  match ':action' => 'static#:action'

end

app/models/card.rb
class Card < ActiveRecord::Base
  attr_accessible :color, :family, :number
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username
  has_many :votes
  belongs_to :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cards }
    end
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
    @card = Card.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/new
  # GET /cards/new.json
  def new
    @card = Card.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/1/edit
  def edit
    @card = Card.find(params[:id])
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(params[:card])

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render json: @card, status: :created, location: @card }
      else
        format.html { render action: "new" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cards/1
  # PUT /cards/1.json
  def update
    @card = Card.find(params[:id])

    respond_to do |format|
      if @card.update_attributes(params[:card])
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card = Card.find(params[:id])
    @card.destroy

    respond_to do |format|
      format.html { redirect_to cards_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  respond_to :erb
  def about
    render "/app/views/shared/steve.erb"
  end
  def contact
    render "/app/views/shared/steve.erb"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.haml
= form_for @card do |f|
  -if @card.errors.any?
    #error_explanation
      %h2= "#{pluralize(@card.errors.count, "error")} prohibited this card from being saved:"
      %ul
        - @card.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :color
    = f.text_field :color
  .field
    = f.label :family
    = f.text_field :family
  .field
    = f.label :number
    = f.number_field :number
  .actions
    = f.submit 'Save'

app/views/cards/edit.html.haml
%h1 Editing card

= render 'form'

= link_to 'Show', @card
\|
= link_to 'Back', cards_path

app/views/cards/index.html.haml
%h1 Listing cards

%table
  %tr
    %th Color
    %th Family
    %th Number
    %th
    %th
    %th

  - @cards.each do |card|
    %tr
      %td= card.color
      %td= card.family
      %td= card.number
      %td= link_to 'Show', card
      %td= link_to 'Edit', edit_card_path(card)
      %td= link_to 'Destroy', card, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Card', new_card_path

app/views/cards/new.html.haml
%h1 New card

= render 'form'

= link_to 'Back', cards_path

app/views/cards/show.html.haml
%p#notice= notice

%p
  %b Color:
  = @card.color
%p
  %b Family:
  = @card.family
%p
  %b Number:
  = @card.number

= link_to 'Edit', edit_card_path(@card)
\|
= link_to 'Back', cards_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestRails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/steve.erb
Hey this is Steve!! Welcome to my page :)